Tank Controller Lib: pHControl_TC Class Reference
pHControl_TC Class Reference
#include <pHControl_TC.h>
Public Member Functions
void bubble ()
void noBubble ()
void driveOutput ()
Private Attributes
const int CO2_REG_PIN = 49
long window_start_time = millis()
Detailed Description
Definition at line 3 of file pHControl_TC.h.
Member Function Documentation
bubble()
void pHControl_TC::bubble () inline
Definition at line 10 of file pHControl_TC.h.
 { digitalWrite(CO2_REG_PIN, LOW); }
References CO2_REG_PIN.
Referenced by driveOutput().
driveOutput()
void pHControl_TC::driveOutput ()
Definition at line 4 of file pHControl_TC.cpp.
{
     long now = millis();
     // Set the output
     // "on time" is proportional to the PID output
     if (now - window_start_time > WINDOW_SIZE) {  // time to shift the Relay Window
         window_start_time += WINDOW_SIZE;
     }
     // on_time may need to be passed in
     if ((on_time > 100) && (one_time > (now - window_start_time))) {
         bubble();
     } else {
         noBubble();
     }
 }
References bubble(), noBubble(), and window_start_time.
noBubble()
void pHControl_TC::noBubble () inline
Definition at line 12 of file pHControl_TC.h.
 { digitalWrite(CO2_REG_PIN, HIGH); }
References CO2_REG_PIN.
Referenced by driveOutput().
Member Data Documentation
CO2_REG_PIN
const int pHControl_TC::CO2_REG_PIN = 49 private
Definition at line 5 of file pHControl_TC.h.
Referenced by bubble(), and noBubble().
window_start_time
long pHControl_TC::window_start_time = millis() private
Definition at line 6 of file pHControl_TC.h.
Referenced by driveOutput().
The documentation for this class was generated from the following files:
src/Devices/pHControl_TC.h
src/Devices/pHControl_TC.cpp